version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  redisdb:
    image: redis
    ports:
      - 6379:6379
  ac1dac:
    build: .
    depends_on:
      - mongodb
      - redisdb
    ports: 
      - 3003:3003